Change to use mule

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,17 +1,11 @@
 #!/usr/bin/env bash
 # bin/use <build-dir>
 
-if [ -f $1/pom.xml ] ||
-   [ -f $1/pom.atom ] ||
-   [ -f $1/pom.clj ] ||
-   [ -f $1/pom.groovy ] ||
-   [ -f $1/pom.rb ] ||
-   [ -f $1/pom.scala ] ||
-   [ -f $1/pom.yaml ] ||
-   [ -f $1/pom.yml ] ; then
-  echo "Java"
+if [ -f $1/pom.xml ] &&
+   [ -f $1/mule-project.xml ] ; then
+  echo "Mule"
   exit 0
 else
-  (>&2 echo "Could not find a pom.xml file! Please check that it exists and is committed to Git.")
+  (>&2 echo "Could not find a pom.xml and mule-project.xml files! Please check that it exists and are committed to Git.")
   exit 1
 fi
